# 1 Constant

## 1.1 일단 import

In [1]:
import tensorflow as tf

2022-11-28 16:52:32.352610: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-28 16:52:32.504234: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-11-28 16:52:33.196533: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda-11.3/lib64
2022-11-28 16:52:33.196593: W tensorflow/compiler/xla/strea

## 1.2 리스트 형을 텐서로~ int

In [2]:
li_ten = tf.constant([1, 2, 3])
li_ten

2022-11-28 16:53:02.869278: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-28 16:53:02.874635: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-28 16:53:02.874871: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-28 16:53:02.875711: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operati

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

## 1.3 혹은 float형 텐서로

In [3]:
li_ten_f = tf.constant([1., 2., 3.])
li_ten_f

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

## 1.4 혹은 튜플을 텐서로

In [4]:
tu_ten = tf.constant(((1, 2, 3), (1, 2, 3)))
tu_ten

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

## 1.5 넘파이를 텐서로

In [5]:
import numpy as np

arr = np.array([1., 2., 3.])
arr_ten = tf.constant(arr)
arr_ten

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

## 1.6 텐서를 numpy로

In [6]:
arr_ten.numpy(), type(arr_ten.numpy())

(array([1., 2., 3.]), numpy.ndarray)

## 1.7 shape이나 dtype을 확인하기

In [7]:
li_ten.shape, tu_ten.shape

(TensorShape([3]), TensorShape([2, 3]))

## 1.8 방금처럼 텐서로 지정하거나

In [8]:
tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

## 1.9 cast를 사용하거나

In [9]:
tf.cast(tensor, dtype=tf.int16)

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 2, 3], dtype=int16)>

## 1.10 1로 채우기

In [10]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

## 1.11 0으로 채우기

In [11]:
tf.zeros((2, 5), dtype="int32")

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

## 1.12 텐서플로우에도 range가

In [12]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [13]:
tf.range(1, 11)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

## 1.13 텐서로 등비수열 만들기

In [14]:
def geometric_sequence(n):
    r = tf.range(n, dtype='int32')
    s = tf.ones(n, dtype=tf.int32) * 2
    return s**r

## 1.14 여기서 알아야할 것은 코딩 기법

In [15]:
print(geometric_sequence(10))

tf.Tensor([  1   2   4   8  16  32  64 128 256 512], shape=(10,), dtype=int32)


## 1.15 랜덤 만들기

In [16]:
shape = (3, 3)
tf.random.normal(shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.33519897, -0.44111612, -1.9443173 ],
       [-0.0290526 , -0.04916233,  1.373018  ],
       [-0.05720217,  0.33631656, -0.27425495]], dtype=float32)>

## 1.16 텐서플로우에서 랜덤시드 관리

In [20]:
tf.random.set_seed(13)
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.5983684], shape=(1,), dtype=float32)
tf.Tensor([0.53933334], shape=(1,), dtype=float32)


## 1.17 한번더

In [21]:
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.27229798], shape=(1,), dtype=float32)
tf.Tensor([0.5121772], shape=(1,), dtype=float32)


## 1.18 시드 설정의 경이로움

In [22]:
tf.random.set_seed(13)
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.5983684], shape=(1,), dtype=float32)
tf.Tensor([0.53933334], shape=(1,), dtype=float32)


# 2 Variable

## 2.1 변수로 선언하기

In [23]:
tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
arr = np.array([[1, 2], [3, 4]])
li = [[1, 2], [3, 4]]

te_var = tf.Variable(tensor)
arr_var = tf.Variable(arr)
li_var = tf.Variable(li)

print(te_var)
print(arr_var)
print(li_var)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>


## 2.2 뭐 변수라도 확인할 수 있는건 다 있다

In [25]:
print("Shape: ", te_var.shape)
print("DType: ", te_var.dtype)
print("AsNumPy: ", te_var.numpy)

Shape:  (2, 2)
DType:  <dtype: 'float32'>
AsNumPy:  <bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>>


## 2.3 메모리를 허비하지 않고 재할당 가능하다

In [26]:
a = tf.Variable([2.0, 3.0])
print("First : ", a, "\n")

a.assign([1, 2])
print("Second : ", a, "\n")

First :  <tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)> 

Second :  <tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)> 



# 3 텐서 연산

## 3.1 덧셈 연산

In [28]:
a = tf.range(6, dtype=tf.int32)
b = 2 * tf.ones(6, dtype=tf.int32)

tf.add(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7], dtype=int32)>

## 3.2 사실

In [29]:
a + b

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7], dtype=int32)>

## 3.3 연산의 종류

- tf.abs : 절대값
- tf.sign : 부호
- tf.round : 반올림
- tf.ceil : 올림
- tf.floor : 내림
- tf.square : 제곱
- tf.sqrt : 제곱근
- tf.maximum : 두 텐서의 각 원소에서 최댓값만 반환
- tf.minimum : 두 텐서의 각 원소에서 최솟값만 반환
- tf.cumsum : 누적합
- tf.cumprod :누적곱

## 3.4 최대값

In [30]:
tf.maximum(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5], dtype=int32)>

## 3.5 연습용 텐서 하나

In [31]:
rank_2 = tf.random.normal((3, 3))
rank_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.9487271 ,  1.3044667 , -1.1531729 ],
       [-0.28560743,  0.48564127, -0.9099395 ],
       [-0.96096003,  1.3391656 , -0.11258006]], dtype=float32)>

## 3.6 첫번째 행

In [32]:
rank_2[0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.9487271,  1.3044667, -1.1531729], dtype=float32)>

## 3.7 첫번째 열, 첫번째 행

In [33]:
rank_2[0, 0]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.9487271>

## 3.8 3차원 짜리

In [34]:
rank_3 = tf.random.normal((3, 3, 3))
rank_3

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-0.1856016 , -1.1418061 ,  0.0194767 ],
        [-2.7855177 ,  1.2621061 , -1.2295452 ],
        [-0.9714309 , -0.35085803,  1.1138306 ]],

       [[ 0.9682026 , -1.9595007 ,  1.0642354 ],
        [ 1.494038  , -1.1601017 ,  1.4813476 ],
        [-0.21271256,  1.0881292 ,  0.31397238]],

       [[-0.52992046,  0.19140598, -0.2779634 ],
        [-1.2172662 ,  0.5619219 , -2.132913  ],
        [ 0.8605408 ,  0.65008086,  0.33721906]]], dtype=float32)>

## 3.9 4차원 짜리

In [35]:
rank_4 = tf.random.normal((3, 3, 3, 3))
rank_4

<tf.Tensor: shape=(3, 3, 3, 3), dtype=float32, numpy=
array([[[[ 1.3927455 , -0.45965314,  0.49407616],
         [ 0.17237075,  0.93350935,  1.6913122 ],
         [ 0.91713065, -0.16278401,  0.3994191 ]],

        [[ 1.3299477 , -0.16608767,  0.52453625],
         [-0.825861  , -0.39364755,  0.15490197],
         [-0.7261836 , -0.21677208,  0.14307553]],

        [[-0.7616838 , -1.7694571 , -1.2084615 ],
         [ 0.15294294,  0.61789715,  0.75220877],
         [-0.9087012 ,  0.34433067, -0.1459559 ]]],


       [[[ 2.2195857 , -0.9483894 , -0.72741896],
         [-0.09788546, -0.74635005,  1.6196522 ],
         [-1.339364  ,  0.10365214,  1.5238657 ]],

        [[ 1.970443  , -1.9742427 ,  1.646089  ],
         [-0.10265194, -0.14842309,  0.6076201 ],
         [ 0.31007034, -0.16753197, -0.6445421 ]],

        [[-0.11728214, -0.38824674,  0.31977358],
         [-0.8027508 , -1.8807936 ,  0.35686776],
         [-1.498092  , -1.8625052 ,  1.2523474 ]]],


       [[[ 1.9372497 , -1.0422

## 3.10 차원의 축소

- tf.reduce_mean : 설정한 축의 평균을 구한다. 
- tf.reduce_max : 설정한 축의 최댓값을 구한다.
- tf.reduce_min : 설정한 축의 최솟값을 구한다.
- tf.reduce_prod : 설정한 축의 요소를 모두 곱한 값을 구한다.
- tf.reduce_sum : 설정한 축의 요소를 모두 더한 값을 구한다.

## 3.11 행렬곱

In [39]:
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
b = tf.constant([[1, 1], [1, 1]], dtype=tf.float32)
tf.matmul(a, b)

2022-11-28 17:13:29.700911: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:630] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [1., 1.]], dtype=float32)>

## 3.11 행렬곱

In [40]:
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
tf.linalg.inv(a)

2022-11-28 17:13:49.899384: I tensorflow/core/util/cuda_solvers.cc:179] Creating GpuSolver handles for stream 0x1b4bdeb0


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5, 0. ],
       [0. , 1. ]], dtype=float32)>

## 3.13 크기나 차원을 변경하는 명령

- tf.reshape : 벡터 행렬의 크기 반환
- tf.transpose : 전치 연산
- tf.expand_dims : 지정한 축으로 차원을 추가
- tf.squeeze : 벡처로 차원을 축소

## 3.14 테스트용 하나

In [41]:
a = tf.range(6, dtype=tf.float32)
print("a    :", a, "\n")

a    : tf.Tensor([0. 1. 2. 3. 4. 5.], shape=(6,), dtype=float32) 



## 3.15 행령의 크기 변경

In [42]:
a_2d = tf.reshape(a, (2, 3)) # 1차원 벡터는 2X3 크기의 2차원 행렬로 변환
print("a     :", a)
print("a_2d  :", a_2d, "\n")

a     : tf.Tensor([0. 1. 2. 3. 4. 5.], shape=(6,), dtype=float32)
a_2d  : tf.Tensor(
[[0. 1. 2.]
 [3. 4. 5.]], shape=(2, 3), dtype=float32) 



## 3.16 전치

In [43]:
a_2d_t = tf.transpose(a_2d) # 2X3 크기의 2차원 행렬을 3X2 크기의 2차원 행렬로 변환
print("a_2d     :", a_2d)
print("a_2d_t:", a_2d_t, "\n")

a_2d     : tf.Tensor(
[[0. 1. 2.]
 [3. 4. 5.]], shape=(2, 3), dtype=float32)
a_2d_t: tf.Tensor(
[[0. 3.]
 [1. 4.]
 [2. 5.]], shape=(3, 2), dtype=float32) 



## 3.17 첫번째 차원 늘리기

In [44]:
a_3d = tf.expand_dims(a_2d, 0) # 2X3 크기의 2차원 행렬을 1X2X3 크기의 3차원 행렬로 변환
print("a_2d     :", a_2d)
print("a_3d  :", a_3d, "\n")

a_2d     : tf.Tensor(
[[0. 1. 2.]
 [3. 4. 5.]], shape=(2, 3), dtype=float32)
a_3d  : tf.Tensor(
[[[0. 1. 2.]
  [3. 4. 5.]]], shape=(1, 2, 3), dtype=float32) 



## 3.18 마지막 차원 늘리기

In [45]:
a_4d = tf.expand_dims(a_3d, 3) # 1X2X3 크기의 3차원 행렬을 1X2X3X1 크기의 4차원 행렬로 변환
print("a_3d     :", a_3d)
print("a_4d  :", a_4d, "\n")

a_3d     : tf.Tensor(
[[[0. 1. 2.]
  [3. 4. 5.]]], shape=(1, 2, 3), dtype=float32)
a_4d  : tf.Tensor(
[[[[0.]
   [1.]
   [2.]]

  [[3.]
   [4.]
   [5.]]]], shape=(1, 2, 3, 1), dtype=float32) 



## 3.19 차원의 크기가 1인것 정리하기

In [46]:
a_1d = tf.squeeze(a_4d)
print("a_4d    :", a_4d)
print("a_1d    :", a_1d, "\n")

a_4d    : tf.Tensor(
[[[[0.]
   [1.]
   [2.]]

  [[3.]
   [4.]
   [5.]]]], shape=(1, 2, 3, 1), dtype=float32)
a_1d    : tf.Tensor(
[[0. 1. 2.]
 [3. 4. 5.]], shape=(2, 3), dtype=float32) 



## 3.20 텐서를 나누거나 합치는 명령

- tf.slice : 특정 부분을 추출
- tf.split : 분할
- tf.concat : 합치기
- tf.tile : 복제-붙이기
- tf.stack : 합성
- tf.unstack : 분리

## 3.21 또 연습용

In [47]:
a = tf.reshape(tf.range(12), (3, 4))
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

## 3.22 슬라이스

In [48]:
tf.slice(a, [0, 1], [2, 3]) # (0, 1)위치에서 (2개, 3개)만큼 뽑아낸다.

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]], dtype=int32)>

## 3.23 가로축을 따라 2개로 분리

In [49]:
a1, a2 = tf.split(a, num_or_size_splits=2, axis=1) # 가로축(axis=1)을 따라 2개로 분할
print(a1)
print(a2)

tf.Tensor(
[[0 1]
 [4 5]
 [8 9]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  3]
 [ 6  7]
 [10 11]], shape=(3, 2), dtype=int32)


## 3.24 합치기

In [50]:
tf.concat([a1, a2], 1) # 가로축(axis=1)을 따라 a1, a2를 합치기

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

## 3.25 가로축 따라 세 개로 확대

In [51]:
tf.tile(a1, [1,3]) # 가로축(axis=1)을 따라 3개로 복사-붙이기

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 0, 1, 0, 1],
       [4, 5, 4, 5, 4, 5],
       [8, 9, 8, 9, 8, 9]], dtype=int32)>

## 3.26 스택은 차원을 늘리면서 합치기

In [52]:
# 3X2 행렬 a1, a2를 추가적인 차원으로 붙여서 2X3X2 고차원 텐서 생성
a3 = tf.stack([a1, a2])
a3

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]], dtype=int32)>